Repository APPSCHOOL1-REPO/finalproject-checkit, pull requests merged in 2023-02, with the labels that each got.

#397 20230226/refactor/model
  CheckIt/CheckIt/Model/Group.swift
  CheckIt/CheckIt/Model/GroupStore.swift
  CheckIt/CheckIt/View/Group/EditGroupView.swift
  CheckIt/CheckIt/View/Group/Main/MakeGroupModalView.swift
Labels: 학진, refactor

#399 [Feat] 동아리를 신고하는 기능 구현
  CheckIt/CheckIt.xcodeproj/project.pbxproj
  CheckIt/CheckIt/Model/Report.swift
  CheckIt/CheckIt/View/Group/CategoryView.swift
  CheckIt/CheckIt/View/Group/ReportView.swift
  CheckIt/CheckIt/ViewModel/ReportStore.swift
Labels: 학진, feature

#401 [Feat] 동아리 신고 성공시 toast -> alert 변경 작업
  CheckIt/CheckIt/View/Group/ReportView.swift
Labels: 학진, feature

#403 [Feat] 사용자가 동아리, 일정 생성시 유의사항을 확인할 수 있도록 처리
  CheckIt/CheckIt/View/Group/CategoryView.swift
  CheckIt/CheckIt/View/Group/Main/MakeGroupModalView.swift
  CheckIt/CheckIt/View/Group/Modifiers.swift
  CheckIt/CheckIt/View/Group/Schedule/AddScheduleView.swift
  CheckIt/CheckIt/View/Group/Schedule/GroupScheduleView.swift
Labels: 학진, feature

#405 [Feat/Style] 문의하기 기능 추가 및 로그아웃 Alert UI 수정
  CheckIt/CheckIt.xcodeproj/project.pbxproj
  CheckIt/CheckIt/View/MyPage/ContactView.swift
  CheckIt/CheckIt/View/MyPage/LogoutAlert.swift
  CheckIt/CheckIt/View/MyPage/QuestionView.swift
Labels: 혜민, feature, style
